# frozen_string_literal: true
source "https://gems.ruby-china.org"

gem 'cocoapods', '~> 1.5.0'
gem 'fastlane', '~> 2.92.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
